============================= test session starts ==============================
platform linux -- Python 3.10.16, pytest-8.3.5, pluggy-1.6.0
rootdir: /home/jn_cndt4/project/code repair/BugAgent/BugAgent_1.3/data/QuixBugs_test
plugins: anyio-4.9.0, timeout-2.4.0
timeout: 5.0s
timeout method: signal
timeout func_only: False
collected 10 items

python_testcases/test_to_base.py ...FFFFFFF                              [100%]

=================================== FAILURES ===================================
_________________________ test_to_base[input_data3-1F] _________________________

input_data = [31, 16], expected = '1F'

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_to_base(input_data, expected):
>       assert to_base(*input_data) == expected
E       AssertionError: assert 'F1' == '1F'
E         
E         - 1F
E         + F1

python_testcases/test_to_base.py:15: AssertionError
_______________________ test_to_base[input_data4-101001] _______________________

input_data = [41, 2], expected = '101001'

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_to_base(input_data, expected):
>       assert to_base(*input_data) == expected
E       AssertionError: assert '100101' == '101001'
E         
E         - 101001
E         + 100101

python_testcases/test_to_base.py:15: AssertionError
________________________ test_to_base[input_data5-134] _________________________

input_data = [44, 5], expected = '134'

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_to_base(input_data, expected):
>       assert to_base(*input_data) == expected
E       AssertionError: assert '431' == '134'
E         
E         - 134
E         + 431

python_testcases/test_to_base.py:15: AssertionError
_________________________ test_to_base[input_data6-14] _________________________

input_data = [27, 23], expected = '14'

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_to_base(input_data, expected):
>       assert to_base(*input_data) == expected
E       AssertionError: assert '41' == '14'
E         
E         - 14
E         + 41

python_testcases/test_to_base.py:15: AssertionError
_________________________ test_to_base[input_data7-2A] _________________________

input_data = [56, 23], expected = '2A'

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_to_base(input_data, expected):
>       assert to_base(*input_data) == expected
E       AssertionError: assert 'A2' == '2A'
E         
E         - 2A
E         + A2

python_testcases/test_to_base.py:15: AssertionError
________________________ test_to_base[input_data8-E75] _________________________

input_data = [8237, 24], expected = 'E75'

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_to_base(input_data, expected):
>       assert to_base(*input_data) == expected
E       AssertionError: assert '57E' == 'E75'
E         
E         - E75
E         + 57E

python_testcases/test_to_base.py:15: AssertionError
________________________ test_to_base[input_data9-749] _________________________

input_data = [8237, 34], expected = '749'

    @pytest.mark.parametrize("input_data,expected", testdata)
    def test_to_base(input_data, expected):
>       assert to_base(*input_data) == expected
E       AssertionError: assert '947' == '749'
E         
E         - 749
E         + 947

python_testcases/test_to_base.py:15: AssertionError
=========================== short test summary info ============================
FAILED python_testcases/test_to_base.py::test_to_base[input_data3-1F] - Asser...
FAILED python_testcases/test_to_base.py::test_to_base[input_data4-101001] - A...
FAILED python_testcases/test_to_base.py::test_to_base[input_data5-134] - Asse...
FAILED python_testcases/test_to_base.py::test_to_base[input_data6-14] - Asser...
FAILED python_testcases/test_to_base.py::test_to_base[input_data7-2A] - Asser...
FAILED python_testcases/test_to_base.py::test_to_base[input_data8-E75] - Asse...
FAILED python_testcases/test_to_base.py::test_to_base[input_data9-749] - Asse...
========================= 7 failed, 3 passed in 0.04s ==========================
